- charts:
  - clusters:
    - master
    - slave
    configuration:
      file: reference to values
      values:
        p1: test
    name: elastic
    src: dev.kuberlab.io/kuberlab/elastic
    version: ^1.2.4
  - clusters:
    - master
    configuration:
      file: reference to values
    name: kuberlab
    src: dev.kuberlab.io/kuberlab/kuberlab
    version: ""
  name: kuberlab
